AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: kebeh.halab.info
          Id: myCustomOrigin
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: https-only
        Enabled: 'true'
        Comment: Somecomment
        DefaultRootObject: kebeh.html

        Aliases:
        - kebeh.halab.info
 
        DefaultCacheBehavior:
          TargetOriginId: 'arn:aws:s3:::kebeh.halab.info'
          ViewerProtocolPolicy: https-only


        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'