AWSTemplateFormatVersion: 2010-09-09
Resources:
  cloudfrontdistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          ViewerProtocolPolicy: https-only
          DefaultTTL: 3600
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: true
          TargetOriginId: 'arn:aws:s3:::soup.halab.info'
        Enabled: true
        Origins:
          - DomainName: 'soup.halab.info.s3-website.eu-west-2.amazonaws.com'
            Id: 'arn:aws:s3:::soup.halab.info'
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
            
          
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${AWS::StackName}